In [4]:
%run -i '../scripts/tw_net_cleaning.py'

In [2]:
%run -i '../scripts/tw_net_analysis.py'

---

In [5]:
'''
Enter combination for statuses to include in dataframe.

days ~ 11-19, previous are for testing
sets = 1-6
calls = 1-5
'''
days = [7]
sets = [1,2,3,4,6]
calls = [1,2,3,4,5]

df = GetDF(days,sets,calls)

df.head()

../scripts/tw_net_cleaning.py:131: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  tweets['hashtags'] = tagStrings

,id_str,text,hashtags,favorite_count,retweet_count,created_time,calltime,day,set,call,userName,user_id,followers_count,friends_count,place_names,place_ids,lang,sources,in_reply_to_status_id_str,in_reply_to_user_id_str
3678,1093659013152235520,I legit just had sex.....its been a minute lol...,,197,197,2019-02-07 18:53:22+00:00,2019-02-08 02:45:41.424380,7,6,5,Brianna Frost Hogan,39138350,154256,69,"Pennsylvania, USA",dd9c503d6c35364b,en,Twitter for Android,None,None
3532,1093659013152235520,I legit just had sex.....its been a minute lol...,,176,176,2019-02-07 18:53:22+00:00,2019-02-08 00:45:39.563471,7,6,4,Brianna Frost Hogan,39138350,154265,69,"Pennsylvania, USA",dd9c503d6c35364b,en,Twitter for Android,None,None
3386,1093659013152235520,I legit just had sex.....its been a minute lol...,,143,143,2019-02-07 18:53:22+00:00,2019-02-07 22:45:31.853193,7,6,3,Brianna Frost Hogan,39138350,154266,69,"Pennsylvania, USA",dd9c503d6c35364b,en,Twitter for Android,None,None
3240,1093659013152235520,I legit just had sex.....its been a minute lol...,,95,95,2019-02-07 18:53:22+00:00,2019-02-07 20:45:33.489565,7,6,2,Brianna Frost Hogan,39138350,154282,69,"Pennsylvania, USA",dd9c503d6c35364b,en,Twitter for Android,None,None
1490,1093524836008235008,Condolences to @PhilMartelliSJU and the entire...,,75,75,2019-02-07 10:00:12+00:00,2019-02-07 17:45:35.971808,7,2,5,Dana O'Neil,33590096,56322,2062,"Pennsylvania, USA",dd9c503d6c35364b,en,Twitter for iPhone,None,None